apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: application
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: application-pod
  name: application-pod
  namespace: application
spec:
  containers:
  - image: paketobuildpacks/httpd:0.7
    name: application-pod
    command: ["httpd", "-k", "start", "-DFOREGROUND"]
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
