apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 4
  selector:   # Label selector
    release: stable
  template:   # Pod template
    metadata:
      name: nginx   # Pod name
      labels:
        app: nginx  # Pod Label
        release: stable
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80