apiVersion: v1
kind: Namespace
metadata:
  name: cloud-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-engineers
  namespace: cloud-engineering
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-07-15T16:16:13Z"
  generation: 1
  labels:
    app: internal-app
  name: internal-app
  namespace: cloud-engineering
  resourceVersion: "2244189"
  uid: f4942163-538e-47d2-98bc-40bef8db0ff0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: internal-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: internal-app
    spec:
      serviceAccount: cloud-engineers
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
